# Not used as wiki.cloudrack.ca will be cloudrack.ca
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
title: CloudRack Wordpress Bash install Script
description: CloudRack Wordpress Bash install Script
show_downloads: false
